/*
Not all line items have the product name. Sometimes the product name changes,
like Elastic Search --> Open Search. Fun, huh? So here we map them back in.
*/
drop table if exists cloudstats.cloudstats_dim_aws_products cascade;

create table cloudstats.cloudstats_dim_aws_products (product_code varchar primary key, product_name varchar);

insert into cloudstats_dim_aws_products values
  ('AmazonCloudFront', 'Amazon CloudFront'),
  ('AWSDataTransfer', 'AWS Data Transfer'),
  ('AmazonECRPublic', 'Amazon Elastic Container Registry Public'),
  ('AmazonSES', 'Amazon Simple Email Service'),
  ('AWSBackup', 'AWS Backup'),
  ('AmazonRDS', 'Amazon Relational Database Service'),
  ('AmazonSageMaker', 'Amazon SageMaker'),
  ('AWSGlue', 'AWS Glue'),
  ('AmazonCloudWatch', 'AmazonCloudWatch'),
  ('awskms', 'AWS Key Management Service'),
  ('AmazonEC2', 'Amazon Elastic Compute Cloud'),
  ('AmazonApiGateway', 'Amazon API Gateway'),
  ('AmazonRoute53', 'Amazon Route 53'),
  ('AmazonSNS', 'Amazon Simple Notification Service'),
  ('AWSQueueService', 'Amazon Simple Queue Service'),
  ('AWSSecretsManager', 'AWS Secrets Manager'),
  ('AmazonECR', 'Amazon EC2 Container Registry (ECR)'),
  ('AWSSecurityHub', 'AWS Security Hub'),
  ('AmazonDocDB', 'Amazon DocumentDB (with MongoDB compatibility)'),
  ('AWSCloudTrail', 'AWS CloudTrail'),
  ('AmazonVPC', 'Amazon Virtual Private Cloud'),
  ('AmazonS3', 'Amazon Simple Storage Service'),
  ('awswaf', 'AWS WAF'),
  ('AmazonGuardDuty', 'Amazon GuardDuty'),
  ('AmazonSimpleDB', 'Amazon SimpleDB'),
  ('AmazonECS', 'Amazon Elastic Container Service'),
  ('AmazonLightsail', 'Amazon Lightsail'),
  ('AmazonQuickSight', 'Amazon QuickSight'),
  ('AWSELB', 'Elastic Load Balancing'),
  ('AmazonES', 'Amazon OpenSearch Service'),
  ('AmazonDynamoDB', 'Amazon DynamoDB'),
  ('CodeBuild', 'CodeBuild'),
  ('AWSEvents', 'CloudWatch Events'),
  ('AWSLambda', 'AWS Lambda'),
  ('AmazonInspectorV2', 'Amazon Inspector'),
  ('AmazonMCS', 'Amazon Keyspaces (for Apache Cassandra)'),
  ('AmazonElastiCache', 'Amazon ElastiCache'),
  ('AWSTransfer', 'AWS Transfer Family'),
  ('AmazonQLDB', 'Amazon Quantum Ledger Database'),
  ('AWSCostExplorer', 'AWS Cost Explorer'),
  ('AWSAmplify', 'AWS Amplify'),
  ('AmazonEFS', 'Amazon Elastic File System'),
  ('AWSConfig', 'AWS Config'),
  ('AmazonKinesisFirehose', 'Amazon Kinesis Firehose'),
  ('AWSXRay', 'AWS X-Ray'),
  ('AmazonStates', 'AWS Step Functions'),
  ('AmazonKinesis', 'Amazon Kinesis'),
  ('AWSCodePipeline', 'AWS CodePipeline'),
  ('AWSGlobalAccelerator', 'AWS Global Accelerator'),
  ('AWSCodeArtifact', 'AWS CodeArtifact'),
  ('AmazonPinpoint', 'Amazon Pinpoint'),
  ('AmazonWorkMail', 'AmazonWorkMail'),
  ('AmazonEKS', 'Amazon Elastic Container Service for Kubernetes'),
  ('AWSCodeCommit', 'AWS CodeCommit'),
  ('AWSSystemsManager', 'AWS Systems Manager'),
  ('AWSDatabaseMigrationSvc', 'AWS Database Migration Service'),
  ('AmazonAthena', 'Amazon Athena'),
  ('AmazonCognito', 'Amazon Cognito'),
  ('AWSElementalMediaStore', 'AWS Elemental MediaStore'),
  ('AWSServiceCatalog', 'AWS Service Catalog'),
  ('AWSElementalMediaConvert', 'AWS Elemental MediaConvert'),
  ('AmazonIVS', 'Amazon Interactive Video Service'),
  ('ElasticMapReduce', 'Amazon Elastic MapReduce'),
  ('AmazonKinesisAnalytics', 'Amazon Kinesis Analytics'),
  ('AmazonRegistrar', 'Amazon Registrar'),
  ('AmazonRedshift', 'Amazon Redshift'),
  ('AppFlow', 'Amazon AppFlow'),
  ('AmazonTimestream', 'Amazon Timestream'),
  ('AmazonChimeFeatures', 'Amazon Chime Features'),
  ('AmazonChime', 'Amazon Chime'),
  ('ComputeSavingsPlans', 'Savings Plans for AWS Compute usage'),
  ('AWSShield', 'AWS Shield'),
  ('AmazonMQ', 'Amazon MQ'),
  ('AWSAppSync', 'AWS AppSync'),
  ('AmazonLocationService', 'Amazon Location Service'),
  ('AmazonFSx', 'Amazon FSx'),
  ('AWSDirectoryService', 'AWS Directory Service'),
  ('AmazonPrometheus', 'Amazon Managed Service for Prometheus'),
  ('AmazonWorkSpaces', 'Amazon WorkSpaces'),
  ('AmazonMSK', 'Amazon Managed Streaming for Apache Kafka'),
  ('AmazonRekognition', 'Amazon Rekognition'),
  ('comprehend', 'Amazon Comprehend'),
  ('AmazonCloudSearch', 'Amazon CloudSearch'),
  ('AmazonKendra', 'Amazon Kendra'),
  ('AmazonSumerian', 'Amazon Sumerian'),
  ('AmazonWorkDocs', 'Amazon WorkDocs'),
  ('ContactCenterTelecomm', 'Contact Center Telecommunications (service sold by AMCS, LLC) '),
  ('AmazonMWAA', 'Amazon Managed Workflows for Apache Airflow')

;
