drop table if exists cloudstats.cloudstats cascade;
CREATE TABLE cloudstats.cloudstats (

    /* dimensions */
    year							character (4) ENCODE lzo,
    month							character varying(2) ENCODE lzo,
    date_month						character (7) ENCODE lzo,
    day_of_week						character (7) ENCODE lzo,
    account_id						character varying(256) ENCODE lzo,
    account_name					character varying(256) ENCODE lzo,
    account_display_name			character varying(515) ENCODE lzo,
    billing_entity					character varying(256) ENCODE lzo,
    legal_entity					character varying(256) ENCODE lzo,
    invoice_id						character varying(256) ENCODE lzo,
    resource_name					character varying(2000) ENCODE lzo,
    line_item_type					character varying(256) ENCODE lzo,
    usage_type						character varying(256) ENCODE lzo,
    usage_type_prefix				character varying(256) ENCODE lzo,
    region_code						character varying(256) ENCODE lzo,
    location						character varying(256) ENCODE lzo,
    operation						character varying(256) ENCODE lzo,
    currency_code					character varying(256) ENCODE lzo,
    pricing_bucket					character varying(256) ENCODE raw,
    product_code					character varying(256) ENCODE lzo,
    product_name					character varying(256) ENCODE lzo,
    bill_product_code				character varying(256) ENCODE lzo,
    bill_product_name				character varying(256) ENCODE lzo,
    product_family					character varying(256) ENCODE lzo,
    product_group					character varying(256) ENCODE lzo,
    product_servicecode				character varying(256) ENCODE lzo,
    pricing_unit					character varying(256) ENCODE lzo,
    pricing_regime					character varying(11) ENCODE lzo,
    product_description				character varying(256) ENCODE lzo,
    savings_plan_arn				character varying(256) ENCODE lzo,
    reserved_instance_arn			character varying(256) ENCODE lzo,
    compute_instance_spec			character varying(385) ENCODE lzo,
    compute_instance_type			character varying(384) ENCODE lzo,
    compute_instance_family			character varying(384) ENCODE lzo,
    compute_instance_type_family	character varying(384) ENCODE lzo,
    compute_availability_zone		character varying(256) ENCODE lzo,
    compute_capacity_status			character varying(256) ENCODE lzo,
    compute_class			        character varying(256) ENCODE lzo,
    compute_processor_name			character varying(256) ENCODE lzo,
    compute_processor_vendor		character varying(256) ENCODE lzo,
    compute_processor_line			character varying(256) ENCODE lzo,
    compute_processor_vcpu			integer ENCODE az64,
    compute_storage					character varying(256) ENCODE lzo,
    compute_os						character varying(256) ENCODE lzo,
    compute_software				character varying(514) ENCODE lzo,
    storage_class					character varying(256) ENCODE lzo,
    storage_volume_type				character varying(256) ENCODE lzo,
    storage_volume_api				character varying(256) ENCODE lzo,
    storage_user_volume				character varying(256) ENCODE lzo,
    days_in_month					integer ENCODE az64

    /* measures */
    record_cnt						bigint ENCODE az64,
    usage							double precision ENCODE raw,
    cost							double precision ENCODE raw,
    cost_mrr						double precision ENCODE raw,
    unblended_cost					double precision ENCODE raw,
    cost_without_edp				double precision ENCODE raw,
    edp_discount					double precision ENCODE raw,
    total_discount					double precision ENCODE raw,
    private_rate_discount			double precision ENCODE raw,
    public_cost						double precision ENCODE raw,
    rate							double precision ENCODE raw,
    public_rate						double precision ENCODE raw,
    storage_total_gb				double precision ENCODE raw,
    storage_total_tb				double precision ENCODE raw,

    /* partition / sort key */
    date							character (10) ENCODE raw
) DISTSTYLE AUTO
SORTKEY
    (date);
